#pragma once
#include <iostream>
#include <string>
#include <cstdint>
#include <iomanip>
#include <thread>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <deque>
#include <unordered_map>
#include <fstream>
#include <sstream>
#include <cmath>
#include <chrono>
#include <random>
#include <stack>
#include <mutex>

#include "ClassesAndStructs.h"
#include "EvalConstants.h"
#include "GlobalParameters.h"
#include "MoveGenConst.h"
#include "ClientConnectionToServer.h"
#include "DebugFunctions.h"
#include "EvalFuntions.h"
#include "MoveExecution.h"
#include "MoveGen.h"
#include "Search.h"
#include "ZobristHashing.h"